name: Postman CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52274286-41383de2-9579-4d7b-9cc3-7ab419bd6d14 -e 52274286-041cf4d0-f40e-403f-81f3-8c4749996b12 --report-events --verbose
