name: Postman CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52238111-c6802f16-2dd9-4c78-97a4-6312f5d5b219 -e 52238111-05494b67-3bd3-4e07-96f6-1a03def33236 --report-events --verbose
